version: "3"
services:
  vue-todo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run serve"
    ports:
      - "8080:8080"
    tty: true
